import React from 'react';
import type { Metadata } from 'next';
import { Header } from '@/components';
import { layoutClassNames } from '@/styles';
import { title } from '@/data/shop';
import './globals.css';

export const metadata: Metadata = {
  title,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className={layoutClassNames}>{children}</div>
      </body>
    </html>
  );
}
