import React, { Suspense } from 'react';
import type { Metadata } from 'next';
import { Header, Footer } from '@/components';
import { layoutClassNames } from '@/styles';
import { title } from '@/data/shop';
import Loading from './loading';
import './globals.css';

export const metadata: Metadata = {
  title,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className={layoutClassNames}>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </div>
        <Footer />
      </body>
    </html>
  );
}
